### ISSUE TITLE
Request to become a maintainer

### ISSUE THREAD

**Issue by hanzohasashi33** [AdiChat/OpenGenus-Slack#113]
I would like to become a maintainer and also like to join the slack channel.
emailid - prasannavenkateshramkumar@gmail.com
github profile - https://github.com/hanzohasashi33

**Comment by hanzohasashi33** [comment]
@AdiChat 
@arnavb

**Comment by arnavb** [comment]
@hanzohasashi33 While I do not have the power to make you a maintainer, you also have to show that you are capable of doing so. Consider reviewing pull requests in cosmos and then @AdiChat will decide.

**Comment by hanzohasashi33** [comment]
Thank you.
I will surely do my best.

**Comment by hanzohasashi33** [comment]
By the way , It shows that I am not authorized to review pull requests while doing so.

**Comment by arnavb** [comment]
You can review pull requests, it's just that they won't be official reviews (they will be shown in grey). They will still be visible.

**Comment by hanzohasashi33** [comment]
Ok , thanks
